### ISSUE TITLE
mixins.json file needs a unique name

### ISSUE THREAD

**Issue by Fourmisain** [Jab125/goblin-traders-fabric#1]
I just learned this, `modid.mixins.json` (and probably also `modid.accesswidener`) needs to have an unique name.
If two mods have the same mixin config name, Fabric Loader 0.12 will [throw a RuntimeException](https://github.com/FabricMC/fabric-loader/blob/a629c73b3b715251f9c76b02d376603a9338b6e9/src/main/java/net/fabricmc/loader/impl/launch/FabricMixinBootstrap.java#L83-L85):
> Non-unique mixin config name

While this doesn't happen with Fabric Loader 0.11, it looks like other mixin configs with the same name would actually be [silently ignored](https://github.com/SpongePowered/Mixin/blob/72d0812084ff2b223f8c11def18158bfa4ad4421/src/main/java/org/spongepowered/asm/mixin/Mixins.java#L108-L111), which is pretty terrifying!

**Comment by 3e2j** [comment]
Being pushed out next patch. Thanks for the heads-up
