### ISSUE TITLE
Potions being unregistered with game restart

### ISSUE THREAD

**Issue by 3e2j** [Jab125/goblin-traders-fabric#11]
Upon a game restart, potions traded from the Vein Trader become Uncraftable Potions until their menu is opened.
This can be fixed by registering the ModPotions file in the GobT files init function. May require a small rewrite of the ModTrades system to accompany this change.

**Comment by Jab125** [comment]
Fixed in 27f072a

P.S. no rewrite, just add a empty function and call it
