### ISSUE TITLE
[Bug] Goblins not spawning

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Jab125/goblin-traders-fabric#23]
### Minecraft Username

ClaudiusMinimus

### Version

1.4.0-BETA-1

### What did you expect?

I am finding that no goblins are spawning in my mod pack, [99 Mods on the Wall: Fabric Edition](https://www.curseforge.com/minecraft/modpacks/ninety-nice-99-mods-on-the-wall-fabric-edition). I am using the default settings with no changes.

	- fabric 0.43.1+1.18
	- fabric-api-base 0.4.1+b4f4f6cda3
	- fabric-api-lookup-api-v1 1.3.5+3ac43d9514
	- goblintraders 1.4.0
	- java 17
	- minecraft 1.18-rc.4

### What did you get?

[latest.log](https://github.com/3e2j/goblin-traders-fabric/files/7622231/latest.log)

**Comment by 3e2j** [comment]
Issue on hold until confirmed

**Comment by 3e2j** [comment]
Closed due to being disproved. -
Goblins spawn underground (check the values in the config)
They spawn as frequently as wandering traders around 14.325 minecraft days

**Comment by Jab125** [comment]
Yeah test it by setting the delay to a very low number and the chance to 100

**Comment by Jab125** [comment]
And there is actually 212￼￼ mods in your mod pack according to latest.log

**Comment by Jab125** [comment]
> Yeah test it by setting the delay to a very low number and the chance to 100

Also, some versions are bugged where the Can Spawn config was inverted and if that's the case, then turn Can Spawn off until the full 1.4.0 is out

It’s fixed in commit 0b198aa64eae55df900cc7ad5f3c84c4e0fc1fb7 for your information, so next update/beta should have the toggle work properly

**Comment by ClaudiusMinimus** [comment]
> And there is actually 212￼￼ mods in your mod pack according to latest.log

There are 94 mods that I added, other mods are added automatically as libraries for mods I specified.

> > Yeah test it by setting the delay to a very low number and the chance to 100
> 
> Also, some versions are bugged where the Can Spawn config was inverted and if that's the case, then turn Can Spawn off until the full 1.4.0 is out
> 
> It’s fixed in commit [0b198aa](https://github.com/3e2j/goblin-traders-fabric/commit/0b198aa64eae55df900cc7ad5f3c84c4e0fc1fb7) for your information, so next update/beta should have the toggle work properly

Awesome! I look forward to testing!

Thanks!
CM
