### ISSUE TITLE
[Minor Bug] visual bug when playing on a fabric server with Goblin Traders (Fabric) when using Goblin Traders (Forge) on Forge

### ISSUE THREAD

**Issue by Jab125** [Jab125/goblin-traders-fabric#26]
### Minecraft Username

Jab125

### Version

1.4.0

### Minecraft Version

1.17.*

### What did you expect?

Stun and potions to sync

### What did you get?

they don't

**Comment by 3e2j** [comment]
Will not fix - due to Forge version being a separate mod from the fabric version
