### ISSUE TITLE
[Bug] Crash on Server Startup

### ISSUE THREAD

**Issue by MajiCoder** [Jab125/goblin-traders-fabric#31]
### Minecraft Username

MajiBoy

### Version

latest commit

### Minecraft Version

1.16.*

### What did you expect?

I expected server to open.

### What did you get?

Server crashed immediately.
Logs: https://pastebin.com/t890y9Vt

**Comment by 3e2j** [comment]
As said in the crash-log
```
A potential solution has been determined:
	 - Install cloth-config2, version 4.12.41 or later.
```
Install Cloth Config - https://www.curseforge.com/minecraft/mc-mods/cloth-config

**Comment by 3e2j** [comment]
I've just seen that this is a 1.16 server issue you're talking about.
Refer to this comment on another issue as I feel it relates closely to this one:
https://github.com/3e2j/goblin-traders-fabric/issues/30#issuecomment-993721863
