### ISSUE TITLE
[Bug] OP trade

### ISSUE THREAD

**Issue by Dejeh** [Jab125/goblin-traders-fabric#36]
### Minecraft Username

Dejeh

### Version

latest commit

### Minecraft Version

1.18.*

### What did you expect?

Goblin Trader trade:
Fishing Rod + Luck of the Sea III -> Fishing Rod w/ Luck of the Sea IV

### What did you get?

The trade gives you a fishing rod with Luck of the Sea V. Is this intended?

(same thing with Lure)

**Comment by 3e2j** [comment]
Intended.
