### ISSUE TITLE
[Bug] Combining enchanted books together makes the output book higher in level

### ISSUE THREAD

**Issue by Dejeh** [Jab125/goblin-traders-fabric#39]
### Minecraft Username

Dejeh

### Version

1.5

### Minecraft Version

1.18.*

### What did you expect?

I combined Sharpness V + Unbreaking I enchanted books in the anvil and get a Sharpness V + Unbreaking I book.

### What did you get?

I got a Sharpness V + Unbreaking III book.

When I removed Goblin traders this was fixed.

**Comment by Jab125** [comment]
<img width="966" alt="Screen Shot 2022-03-27 at 4 46 34 pm" src="https://user-images.githubusercontent.com/67534807/160268506-944c5b39-a833-4a53-bb47-66c7a2bdf09d.png">
@Dejeh cannot reproduce.

You can reopen the issue if you can show me the bug.
