### ISSUE TITLE
[Bug] Trade window not opening

### ISSUE THREAD

**Issue by DeadpanSausage** [Jab125/goblin-traders-fabric#49]
### Minecraft Username

Nebula4121

### Version

1.5.2

### Minecraft Version

1.19.x

### What did you expect?

To view trades

### What did you get?

Sometimes the trade window will open, sometimes it does not, I have no idea how to reproduce this issue as it seems to happen at random

**Comment by 3e2j** [comment]
As there is no current way to replicate this issue, I'm marking this as closed.
